<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Domain\BookOnline.Domain\BookOnline.Domain.csproj" />
    <ProjectReference Include="..\FinancialBookStore.Domain\FinancialBookStore.Domain.csproj" />
    <ProjectReference Include="..\LibraryOnline.Domain\LibraryOnline.Domain.csproj" />
  </ItemGroup>

</Project>
